app/__init__.py
from flask import Flask

from app.db_manager import db

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://pinkikki:password@192.168.33.10:5432/hero_test'
db.init_app(app)

from .views import hero

app.register_blueprint(hero.mod)

app/views/hero.py
from flask import Blueprint, render_template, request

from app import db_manager
from app.db_manager import Bug

mod = Blueprint('hero', __name__)


@mod.route('/', methods=['GET'])
def index():
    return render_template("hero/register.html")


@mod.route('/register', methods=['POST'])
def register():
    scene_name = request.form['scene_name']
    content = request.form['content']
    print(f'scene_name:{scene_name},content:{content}')

    bug = Bug(scene_name, content)
    bug.insert()
    db_manager.commit()

    return render_template("hero/register.html")


@mod.route('/delete', methods=['POST'])
def delete():
    bug = Bug.query.get(request.form['id'])
    bug.delete()
    db_manager.commit()


@mod.route('/show', methods=['GET'])
def show():
    bugs = Bug.query.all()
    return render_template("hero/show.html", bugs=bugs)

app/templates/hero/layout.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8"/>
    <title>summer-holiday-hero</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js"></script>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

app/templates/hero/register.html
{% extends "hero/layout.html" %}
{% block content %}
    <div class="grid-container">
        <div class="grid-y medium-grid-frame">
            <div class="cell shrink header medium-cell-block-container">
                <div class="grid-x grid-padding-x callout">
                    <div class="cell medium-1">
                        <img src="{{ url_for('static', filename='emo.png') }}"/>
                    </div>
                    <div class="cell medium-11">
                        <h3>bug registration</h3>
                    </div>
                </div>
            </div>
            <div class="cell medium-auto medium-cell-block-container">
                <div class="grid-x grid-margin-x">
                    <div class="cell medium-3 medium-cell-block-y">
                        <div class="callout secondary">
                            <h4>menu</h4>
                            <ul class="vertical menu">
                                <li><a href="{{ url_for('hero.show') }}">bug list</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="cell medium-9 medium-cell-block-y">
                        <form action="{{ url_for('hero.register') }}" method="post">
                            <label>
                                scene name<input type="text" name="scene_name"/>
                            </label>
                            <label>
                                content<textarea name="content"></textarea>
                            </label>
                            <div style="text-align: center">
                                <button type="submit" class="hollow button secondary">登録</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="cell shrink footer">
                copylight 2018
            </div>
        </div>
    </div>
{% endblock %}

app/templates/hero/show.html
{% extends "hero/layout.html" %}
{% block content %}
    <div class="grid-container">
        <div class="grid-y medium-grid-frame">
            <div class="cell shrink header medium-cell-block-container">
                <div class="grid-x grid-padding-x callout">
                    <div class="cell medium-1">
                        <img src="{{ url_for('static', filename='emo.png') }}"/>
                    </div>
                    <div class="cell medium-11">
                        <h3>bug list</h3>
                    </div>
                </div>
            </div>
            <div class="cell medium-auto medium-cell-block-container">
                <div class="grid-x grid-margin-x">
                    <div class="cell medium-3 medium-cell-block-y">
                        <div class="callout secondary">
                            <h4>menu</h4>
                            <ul class="vertical menu">
                                <li><a href="{{ url_for('hero.show') }}">bug list</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="cell medium-9 medium-cell-block-y">
                        <table>
                            <thead>
                            <tr>
                                <th>no</th>
                                <th>scene_name</th>
                                <th>content</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for bug in bugs %}
                                <tr>
                                    <td>{{ bug.id }}</td>
                                    <td>{{ bug.scene_name }}</td>
                                    <td>{{ bug.content }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="cell shrink footer">
                copylight 2018
            </div>
        </div>
    </div>
{% endblock %}